apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.11.2
    helm.sh/chart: argo-cd-7.0.0
    k8slens-edit-resource-version: v1
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd
  managedFields:
    - manager: terraform-provider-helm_v2.14.0_x5
      operation: Update
      apiVersion: v1
      time: '2024-07-04T09:08:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:admin.enabled: {}
          f:application.instanceLabelKey: {}
          f:exec.enabled: {}
          f:server.rbac.log.enforce.enable: {}
          f:statusbadge.enabled: {}
          f:timeout.hard.reconciliation: {}
          f:timeout.reconciliation: {}
          f:url: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
    - manager: node-fetch
      operation: Update
      apiVersion: v1
      time: '2024-08-12T08:33:42Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:accounts.gcrreader: {}
        f:metadata:
          f:labels:
            f:k8slens-edit-resource-version: {}
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-cm
data:
  accounts.gcrreader: login
  accounts.gcrsetter: login
  admin.enabled: 'true'
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'false'
  server.rbac.log.enforce.enable: 'false'
  statusbadge.enabled: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://argocd.example.com
