replicaCount: 1
appName: sample
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 30
canary: "False"
jiraId: test-123
port: 8080
targetPort: 8080
appKind: "microservice"
repoUrl: https://github.com/Adebusy/gen_ai_apps_onboarding.git
namespace: argocd
appNamespace: mfa
