{{- range $key, $values := .Values.workstreamapps -}}
{{- range $value := $values -}}
---
{{ $filename := split "." $value }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $key }}-{{ $filename._0 }}"
  namespace: argocd
spec:
  generators:
    - list:
        elements:
         - cluster: int
           url: https://kubernetes.default.svc
           revision: GEN-AI-INT-01
  template:
    metadata:
      name: "{{"{{"}}cluster{{"}}"}}-{{ $key }}-{{ $filename._0 }}"
    spec:
      sources:
       - repoURL: {{ $.Values.repoUrl }}
         targetRevision: '{{"{{"}}revision{{"}}"}}'
         path: helm-charts
         helm:
          valueFiles:
          - $manifestrepo/manifests/{{ $key }}/{{ $.Values.env.name }}/immutable/{{ $value }}
          - "/app-charts/env-configs/int/values.yaml"
          - "/parent-app-chart/values.yaml"
       - repoURL: 'https://pscode.lioncloud.net/coreai-platform-team/coreai-apps-mainfest.git'
         targetRevision: GEN-AI-INT-01
         ref: manifestrepo
      targetRevision: HEAD
      ref: values
      project: "{{ $key }}-{{"{{"}}cluster{{"}}"}}-{{ $.Values.env.region }}"
      syncPolicy:
        {{- if or (eq $key "audworkstream") (eq $key "dataworkstream") }}
        automated:
          selfHeal: true
          prune: true
        {{- end }}
        syncOptions:
          - CreateNamespace=false
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: {{ $.Values.appNamespace }}
{{ end -}}
{{- end -}}
