{{- if or (eq .Values.appKind "microservice") (eq .Values.appKind "web")  }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.image.repository }}"
  name: "{{ .Values.image.repository }}-svc"
  namespace: "{{ .Values.appNamespace }}-ns"
spec:
  ports:
  {{- range $v := .Values.targetports }}
  - name: {{ $v.name }}
    port: {{ $v.value }}
    protocol: TCP
    targetPort: {{ $v.value }}
  {{- end }}
  selector:
    app: "{{ .Values.image.repository }}"
  sessionAffinity: None
  type: ClusterIP
{{- end }}
