{{- if eq .Values.deployConfigMap true }}
apiVersion: v1
data:
{{- range $key, $val := .Values.configMap }}
   {{ $key }} : {{ $val | quote }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ .Values.image.repository }}-cm
  namespace: "{{ .Values.appNamespace }}-ns"
{{- end }}
