{{- if (.Values.secrets ) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.image.repository }}-es
  namespace: {{ .Values.appNamespace }}-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: css-{{ .Values.keyVault | default "kvintcusclient0shared" }}
  target:
    name: {{ .Values.image.repository }}
    creationPolicy: Owner
  data:
{{- range $key, $val := .Values.secrets }}
  - secretKey: {{ $val }}
    remoteRef:
      key: {{ $key }}
{{- end }}
{{- end }}
